// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegisteredDoctors.Data;

namespace RegisteredDoctors.Migrations
{
    [DbContext(typeof(RegisteredDoctorsContext))]
    partial class RegisteredDoctorsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("RegisteredDoctors.Data.Models.RegisteredDoctor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResgitrationNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SanctionStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Specailty")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("registeredDoctors");
                });
#pragma warning restore 612, 618
        }
    }
}
